const SUBJECTS_CACHE_KEY = "MKONEVIEW_SUBJECTS_PID_studentId_GRADE_ID_gradeId";

// in seconds
const SUBJECTS_CACHE_KEY_EXPIRATION = 3600;

module.exports = { SUBJECTS_CACHE_KEY, SUBJECTS_CACHE_KEY_EXPIRATION };
